/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.yadira.pe.cpresentacion;

import com.yadira.pe.cmodelo.Venta;
import com.yadira.pe.cnegocio.VentaBO;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class JPVenta extends javax.swing.JPanel {

   private VentaBO tdbo; // Asegúrate de inicializar esto
    Venta td = new Venta();
    String idVenta;

    
     public JPVenta() {
        initComponents();

        tdbo = new VentaBO(); // Inicializa la instancia de TipoDocumentoBO
        listarTipoDocumento(); // Cargar los tipos de documentos al inicializar
    }

    public void listarTipoDocumento() {
        tdbo.listarVentas(registroventas);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPVenta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textIDCLIENTE = new javax.swing.JTextField();
        textIDBILLETE = new javax.swing.JTextField();
        textFECHA = new javax.swing.JTextField();
        textHORA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        registroventas = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        JPVenta.setBackground(new java.awt.Color(202, 236, 235));

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        jLabel1.setText("Registro  De  Ventas -  Compañia Nuevo Peru Bank");

        textIDCLIENTE.setBackground(new java.awt.Color(255, 255, 242));
        textIDCLIENTE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textIDCLIENTE.setBorder(null);
        textIDCLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDCLIENTEActionPerformed(evt);
            }
        });

        textIDBILLETE.setBackground(new java.awt.Color(255, 255, 242));
        textIDBILLETE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textIDBILLETE.setBorder(null);
        textIDBILLETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDBILLETEActionPerformed(evt);
            }
        });

        textFECHA.setBackground(new java.awt.Color(255, 255, 242));
        textFECHA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFECHA.setBorder(null);
        textFECHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFECHAActionPerformed(evt);
            }
        });

        textHORA.setBackground(new java.awt.Color(255, 255, 242));
        textHORA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textHORA.setBorder(null);
        textHORA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHORAActionPerformed(evt);
            }
        });

        jLabel5.setText("ID_CLIENTE:");

        jLabel6.setText("ID BILLETE:");

        jLabel7.setText("HORA DE VENTA:");

        jLabel8.setText("FECHA DE VENTA:");

        registroventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(registroventas);

        btnLimpiar.setBackground(new java.awt.Color(204, 238, 206));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(255, 207, 118));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(204, 238, 206));
        btnModificar.setText("modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 207, 118));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPVentaLayout = new javax.swing.GroupLayout(JPVenta);
        JPVenta.setLayout(JPVentaLayout);
        JPVentaLayout.setHorizontalGroup(
            JPVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPVentaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(JPVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPVentaLayout.createSequentialGroup()
                                .addGroup(JPVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(463, 463, 463))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPVentaLayout.createSequentialGroup()
                                .addGroup(JPVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textHORA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                                    .addComponent(textIDBILLETE, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textIDCLIENTE, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(238, 238, 238))
                            .addGroup(JPVentaLayout.createSequentialGroup()
                                .addComponent(textFECHA, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(JPVentaLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(JPVentaLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(JPVentaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPVentaLayout.setVerticalGroup(
            JPVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JPVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPVentaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textIDCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textIDBILLETE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFECHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textHORA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPVentaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(JPVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPVentaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(JPVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpiar)
                            .addComponent(btnGuardar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPVentaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(JPVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar))
                        .addGap(80, 80, 80))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textIDCLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDCLIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDCLIENTEActionPerformed

    private void textIDBILLETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDBILLETEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDBILLETEActionPerformed

    private void textFECHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFECHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFECHAActionPerformed

    private void textHORAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHORAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHORAActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        initComponents();

        textIDCLIENTE.setText("");
        textIDBILLETE.setText("");
        textFECHA.setText("");
        textHORA.setText("");

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       /* try {
            td.setId_venta(textIDCLIENTE.getText());
            td.setId_cliente(textIDBILLETE.getText());
            td.setId_billete(textFECHA.getText());
            td.setHora_venta(textHORA.getText());
           

            String smg = tdbo.agregarVenta(td);
            JOptionPane.showMessageDialog(null, ":) se guardo corectamente" + smg);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: al guardar Tipo documento ");
        }
        }
        public boolean valida(){
            if (textIDCLIENTE.getText().equals("")) {
                JOptionPane.showMessageDialog(null, ":) NOMBRE ES REQUERIDO");
                return false;
            } else if (textIDBILLETE.getText().equals("")) {
                JOptionPane.showMessageDialog(null, ":) APELLIDOS ES REQUERIDO");
                return false;
            } else if (textFECHA.getText().equals("")) {
                JOptionPane.showMessageDialog(null, ":) DNI ES REQUERIDO");
                return false;
            } else if (textHORA.getText().equals("")) {
                JOptionPane.showMessageDialog(null, ":) DIRECCION ES REQUERIDO");
                return false;
            
            
            }

            // If all validations pass
            return true;*/
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
      /*  try {

            td.setId_venta(Integer.parseInt());
            td.setNombre(textIDCLIENTE.getText());
            td.setSiglas(textIDBILLETE.getText());
            td.setNacionalidad(textFECHA.getText());
            td.setEstado(textHORA.getText());
            tdbo.modificartipodocumento(td);
            listarTipoDocumento();
            JOptionPane.showMessageDialog(null, ":) se altualizo corectamente");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: al altualizar Tipo documento ");

        }*/

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     /*   try {
            String id_cliente = null;
            //            TipoDocumento tdf = new TipoDocumento();
            td.setId_cliente(Integer.parseInt(id_cliente));
            tdbo.eliminarCliente(td);
            listarCliente();
        } catch (Exception diego) {
            JOptionPane.showMessageDialog(null, "Error" + diego.getMessage());

        }*/
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPVenta;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable registroventas;
    private javax.swing.JTextField textFECHA;
    private javax.swing.JTextField textHORA;
    private javax.swing.JTextField textIDBILLETE;
    private javax.swing.JTextField textIDCLIENTE;
    // End of variables declaration//GEN-END:variables
}
